<img src="../../../imgs/CampQMIND_banner.png">

# Logistic Regression

This notebook will demonstrate how logistic regression works by first implementing it in numPy and in scikit-learn.


<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Logistic-Regression" data-toc-modified-id="Logistic-Regression-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Logistic Regression</a></span></li><li><span><a href="#Learning-Outcomes" data-toc-modified-id="Learning-Outcomes-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Learning Outcomes</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Cross-Entropy-Loss" data-toc-modified-id="Cross-Entropy-Loss-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Cross Entropy Loss</a></span></li></ul></li></ul></li><li><span><a href="#Scikit-learn-implementation-of-Logistic-Regression" data-toc-modified-id="Scikit-learn-implementation-of-Logistic-Regression-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Scikit-learn implementation of Logistic Regression</a></span></li><li><span><a href="#Resources" data-toc-modified-id="Resources-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Resources</a></span></li></ul></div>

In [1]:
from IPython.display import IFrame
IFrame('https://www.youtube.com/embed/yIYKR4sgzI8',560,315)

The cost function for linear regression: $J_{\theta} = \frac{1}{m}\sum_{1}^{m}\cdot\frac{1}{2}\cdot(h_{\theta}(x^{(i)}) - y^{(i)})^2$

The new predictor: $h_{\theta}(x^{(i)}) = \frac{1}{1 + e^{-\theta^T{x(i)}}}$

The problem is with the new predictor $J_{\theta}$ is no longer convex and thus we can't optimize it.

### Cross Entropy Loss

$$cost(h_{\theta}(x),y)= \left\{   \begin{array}{lr}        -log(h_{\theta}(x)) & y= 1 \\       -log(1 - h_{\theta}(x)) & y = 0       \end{array}\right.$$

We can solve this with gradient descent.

$$\theta_{j} := \theta_{j} - \alpha\frac{\partial{J}}{\partial\theta_{j}}J_{\theta}$$

Where the partial is $$\frac{\partial{J}}{\partial\theta_{j}} = \frac{1}{m}\sum_{i=1}^m(h_{\theta}(x^i) - y^i)*x^i_j$$

Using this, we very easily implement our own logistic regression.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../../data/scaled.csv")
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    data.drop("species", axis=1), data.species)

In [4]:
def cross_entropy_loss(y_pred,target):
    return -np.mean((target*np.log1p(y_pred)+(1-target)*np.log1p(1-y_pred)))

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
theta = np.zeros(X_train.shape[1])
print("Shape of Theta is",theta.shape)
b = np.random.uniform(0,1,1)
print("Shape of Bias is",b.shape)

lr = 0.1
for _ in range(10000):
    prediction = sigmoid(X_train @ theta + b)
    partial = (prediction - y_train) @ X_train
    theta = theta - lr * partial / len(X_train)
    b = b - lr * np.average((prediction - y_train))
    if _ % 5000 == 0:
        loss = cross_entropy_loss(prediction,y_train)
        print(loss)

Shape of Theta is (5,)
Shape of Bias is (1,)
-0.3530470384607948


/Users/mac/anaconda3/envs/QMIND2/lib/python3.7/site-packages/pandas/core/series.py:679: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)


-0.6898801790055923


In [7]:
theta.values

array([-0.50470928,  6.5950563 , 11.93656335, -3.34549615, -5.33601861])

In [8]:
b

array([14.4480871])

In [9]:
from sklearn.metrics import log_loss

preds = sigmoid(X_test @ theta + b)
pred = preds.round()
log_loss(y_test,preds)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        15

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



# Scikit-learn implementation of Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
preds = clf.predict(X_test)
print(classification_report(y_test,preds))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        15

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [12]:
clf.coef_

array([[-1.04696541, -0.10993547,  0.03467974, -0.24159344, -0.25769079]])

In [13]:
cross_entropy_loss(preds,y_test)

-0.6931471805599451

In [14]:
log_loss(y_test,preds)

9.992007221626415e-16

# Resources
- https://towardsdatascience.com/logistic-regression-explained-9ee73cede081